In [ ]:
import pandas as pd
import nfl_data_py as nfl

years = range(2014,2024)
data = nfl.import_combine_data(years)

In [ ]:
data.groupby('draft_year').count()

,season,draft_team,draft_round,draft_ovr,pfr_id,cfb_id,player_name,pos,school,ht,wt,forty,bench,vertical,broad_jump,cone,shuttle
draft_year,,,,,,,,,,,,,,,,,
2014.0,223,223,223,223,223,204,223,223,223,223,223,216,170,185,181,154,158
2015.0,213,213,213,213,213,199,213,213,213,213,213,212,155,173,171,149,155
2016.0,214,214,214,214,214,199,214,214,214,214,214,213,161,183,181,139,144
2017.0,222,222,222,222,222,211,222,222,222,222,222,189,167,189,188,143,144
2018.0,212,212,212,212,212,190,212,212,212,212,212,170,156,165,164,125,133
2019.0,217,217,217,217,217,208,217,217,217,217,217,178,164,177,175,135,143
2020.0,230,230,230,230,230,224,230,230,230,230,230,178,149,166,160,104,106
2021.0,193,193,193,193,193,189,193,193,193,178,179,167,141,170,158,137,141
2022.0,223,223,223,223,223,209,223,223,223,223,223,168,51,159,153,66,75
2023.0,190,190,190,190,190,190,190,190,190,190,190,127,62,141,139,42,48